version: 2.1

orbs:
  buildpulse: workshop64/buildpulse@0.8

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.4

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Run tests
          command: bundle exec rake

      - buildpulse/upload:
          path: test/reports
          account-id: 68192324 # Replace this value with your BuildPulse account ID
          repository-id: 248515673 # Replace this value with your BuildPulse repository ID
